import { Inter } from "next/font/google";
import "./globals.css";

// import Header from "@/lib/modules/templates/Header/Header";
import { Suspense } from "react";
import Nav from "@/lib/modules/templates/components/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Assegai",
  description: "Assegai generated by next app",
};

export default function RootLayout({ children, channel  }) {
  return (
    <>
        <html lang="en" className={inter.variable}>
      <body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
        <Nav />
        <Suspense>
          <main>{children}</main>
        </Suspense>
      </body>
    </html>
    
    </>
  );
}
