import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Header from "@/lib/modules/templates/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ASSEGAI",
  description: "Assegai generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" className={inter.variable}>
        <body className="bg-white text-black">
          <Header/>
          <Suspense>
            <main>{children}</main>
          </Suspense>
        </body>
      </html>
    </>
  );
}
